#!/bin/bash
# lab1

scriptName="$(readlink -f "$0")"
scriptDir=$(command dirname -- "${scriptName}")
PS4='\033[0;33m+$?(${BASH_SOURCE}:${LINENO}):\033[0m ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

die() {
    builtin echo "ERROR($(basename ${scriptName})): $*" >&2
    builtin exit 1
}

main() {
    echo "args: $*"
}

[[ -z ${sourceMe} ]] && {
    main "$@"
    builtin exit
}
command true
